### ISSUE TITLE
Short-term Todo

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#148]
These should be done in the short term, in the order of priority:
- [ ] https://github.com/fangfufu/httpdirfs/issues/147
- [ ] https://github.com/fangfufu/httpdirfs/issues/143
- [ ] https://github.com/fangfufu/httpdirfs/issues/111
- [ ] https://github.com/fangfufu/httpdirfs/issues/116
- [ ] https://github.com/fangfufu/httpdirfs/issues/95
