### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#77]
This issue is mainly for me to keep track of what I want to do. 
- [x] ~~Split into two binaries and the associated documentation changes (``httpdirfs`` and ``subsonicfs``)~~  (Abandoned)
- [x] Improve debug functions
- [x] Automatic generation of man page with proper description
- [x] Contact maintainer for a new Debian package
